# Modify this config file to include your personal
#     Open Weather Map API key and location
# Also: rename 'fake-secrets.ini' to 'secrets.ini'
[Key]
api_key = ###########

[Location]
lat = ###########
lon = ###########
[Settings]
# Can be imperial, metric, or standard
units = ###########